### ISSUE TITLE
Create Post without tag will make exception on post list

### ISSUE THREAD

**Issue by BionStt** [EdiWang/Moonglade#127]
haai Edi,
please give me some advice how to resolve this issue..

![test1](https://user-images.githubusercontent.com/43228630/57187836-4d1e2000-6f1f-11e9-9327-2030b37c2ca1.jpg)

**Comment by EdiWang** [comment]
@BionStt What's the reproduce steps?

**Comment by BionStt** [comment]
sorry @EdiWang ,
please check this "CreateNewPost" when i create new post. it didn't put data into "PostTag" in database.so PostTag always null value. 


   public Response<Post> CreateNewPost(CreateEditPostRequest request)
        {
            void ApplyDefaultValuesOnPost(Post postModel)
            {
                if (postModel.Id == Guid.Empty)
                {
                    postModel.Id = Guid.NewGuid();
                }
                if (string.IsNullOrWhiteSpace(postModel.Slug))
                {
                    postModel.Slug = postModel.Id.ToString();
                }

                if (null == postModel.PostExtension)
                {
                    postModel.PostExtension = new PostExtension
                    {
                        Hits = 0,
                        Likes = 0
                    };
                }
            }

            try
            {
                var postModel = new Post
                {
                    CommentEnabled = request.EnableComment,
                    Id = request.PostId,
                    PostContent = HttpUtility.HtmlEncode(request.HtmlContent),
                    ContentAbstract = Utils.GetPostAbstract(request.HtmlContent, AppSettings.PostSummaryWords),
                    CreateOnUtc = DateTime.UtcNow,
                    Slug = request.Slug.ToLower().Trim(),
                    Title = request.Title.Trim(),
                    PostPublish = new PostPublish
                    {
                        IsDeleted = false,
                        IsPublished = request.IsPublished,
                        PubDateUtc = request.IsPublished ? DateTime.UtcNow : (DateTime?)null,
                        ExposedToSiteMap = request.ExposedToSiteMap,
                        IsFeedIncluded = request.IsFeedIncluded,
                        Revision = 0,
                        ContentLanguageCode = request.ContentLanguageCode
                    }
                };

                // add default values if fields are not assigned
                ApplyDefaultValuesOnPost(postModel);

                // check if exist same slug under the same day
                if (_postRepository.Any(p =>
                    p.Slug == postModel.Slug &&
                    p.PostPublish.PubDateUtc.GetValueOrDefault().Date == DateTime.UtcNow.Date))
                {
                    var uid = Guid.NewGuid();
                    postModel.Slug += $"-{uid.ToString().ToLower().Substring(0, 8)}";
                    Logger.LogInformation($"Found conflict for post slug, generated new slug: {postModel.Slug}");
                }

                // add categories
                if (null != request.CategoryIds && request.CategoryIds.Count > 0)
                {
                    foreach (var cid in request.CategoryIds)
                    {
                        if (_categoryRepository.Any(c => c.Id == cid))
                        {
                            postModel.PostCategory.Add(new PostCategory
                            {
                                CategoryId = cid,
                                PostId = postModel.Id
                            });
                        }
                    }
                }

                // add tags
                if (null != request.Tags && request.Tags.Count > 0)
                {
                    var tagsList = new List<Tag>();
                    foreach (var item in request.Tags)
                    {
                        var tag = _tagRepository.Get(q => q.DisplayName == item);
                        if (null == tag)
                        {
                            // for new tags
                            var newTag = new Tag
                            {
                                DisplayName = item,
                                NormalizedName = Utils.NormalizeTagName(item)
                            };

                            tagsList.Add(newTag);
                            _tagRepository.Add(newTag);
                        }
                        else
                        {
                            // existing tags
                            tagsList.Add(tag);
                        }
                    }

                    tagsList.ForEach(t => postModel.PostTag.Add(new PostTag
                    {
                        TagId = t.Id,
                        PostId = postModel.Id
                    }));
                }

                _postRepository.Add(postModel);
                Logger.LogInformation($"New Post Created Successfully. PostId: {postModel.Id}");
                return new SuccessResponse<Post>(postModel);
            }
            catch (Exception ex)
            {
                Logger.LogError(ex, $"Error in {nameof(CreateNewPost)}");
                return new FailedResponse<Post>((int)ResponseFailureCode.GeneralException);
            }
        }

**Comment by EdiWang** [comment]
Hi @BionStt , it does not matter if there isn't any data in the database. When creating a new post, the system will check if your tag is new or existing. For new tags, it will be automatically created. 

In fact, when you setup the blog code and run for the first time, it will create a default post with 2 tags. See https://github.com/EdiWang/Moonglade/blob/master/src/Moonglade.Web/Startup.cs#L353 

I still don't know how **exactly** did you ran into this exception. Could you describe the **detailed steps** to reproduce the issue? 

P.S. For bugs, please use the bug issue template for best understanding.

**Comment by EdiWang** [comment]
And PostTag is the many-to-many association table. Generally, you don't have to manually write SQL and update database for that.

**Comment by EdiWang** [comment]
@BionStt I am able to reproduce the issue when creating a new post WITHOUT any tag. It's a valid bug. Investigating now.

**Comment by EdiWang** [comment]
@BionStt please check latest code on 'dev' branch, f1e3e8d should workaround this issue for now. The post list still needs some refact and redesign to completely avoid Tracking in EF.

**Comment by EdiWang** [comment]
Fixed in #128

**Comment by BionStt** [comment]
thank you @EdiWang.
