### ISSUE TITLE
Use /avatar to route the avatar.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#171]
I suggest to use /avatar to route the avatar.

Not /get-avatar

<img width="1090" alt="WeChat Image_20190524135202" src="https://user-images.githubusercontent.com/19531547/58305587-3175ad80-7e2b-11e9-8532-c819567d3e34.png">

**Comment by EdiWang** [comment]
Thanks for your suggestion. I agree with this.
