### ISSUE TITLE
Pick icon from gravatar.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#184]
Now that you have already known the commenters' email.  Why not pick the avatar from gravatar? Please bing `Gravatar` [here](https://cn.bing.com/search?q=gravatar)

![WeChat Image_20190531154013](https://user-images.githubusercontent.com/19531547/58689798-95175200-83ba-11e9-9c08-640831e0b107.png)

That is simple and cool!

**Comment by Anduin2017** [comment]
Hi, any plan?

**Comment by EdiWang** [comment]
@Anduin2017 likely for July release

**Comment by EdiWang** [comment]
Consider using this: https://github.com/AndrewFreemantle/Gravatar-HtmlHelper

**Comment by EdiWang** [comment]
A more ASP.NET Corelish solution may be: https://dotnetthoughts.net/aspnet-core-gravatar-taghelper/

**Comment by EdiWang** [comment]
Released in v10.0.7120 / Tag 1d9c9db
