### ISSUE TITLE
Show "time ago" for publish date in post-slug page

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Moonglade#206]
Use @Anduin2017 's jquery-utc-time library to show "time ago" for publish date.

**Comment by EdiWang** [comment]
Blocker: https://github.com/Anduin2017/jquery-utc-time/issues/2

**Comment by Anduin2017** [comment]
Haha. Will resolve.

**Comment by EdiWang** [comment]
Closed as won't fix.

**Comment by Anduin2017** [comment]
Please consider `npm` as your front-end package manager for `npm` is more 清真 in the front-end area.

**Comment by EdiWang** [comment]
No, npm is too heavy for moonglade, it's not a front-end central project. libman is the best choice for moonglade.
