### ISSUE TITLE
The first-time run will cause git to track a lot of meaningless changes

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#262]
![image](https://user-images.githubusercontent.com/19531547/65959786-81254f00-e485-11e9-92c3-480b3e1feeaa.png)

**Comment by EdiWang** [comment]
Good catch. I will add these build generated files to gitignore

**Comment by EdiWang** [comment]
Fixed, thanks for reporting this fracking issue @Anduin2017
