### ISSUE TITLE
Allow comment without review.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#264]
Comment with a review is a Chinese rule. Not an international one. Shall be configurable.

**Comment by EdiWang** [comment]
So that you will get tons of spams....

This is why wordpress also need comments to be reviewed.

**Comment by Anduin2017** [comment]
But I am a person who is working for internet freedom. Comment review violates the values of freedom of speech. As for spams, we can limit the frequency and the IP to avoid them.

**Comment by EdiWang** [comment]
Nice freedom:

![image](https://user-images.githubusercontent.com/3304703/65960857-fb56d300-e487-11e9-9da0-ec04f7586088.png)

Same thing for Wordpress:

![image](https://user-images.githubusercontent.com/3304703/65960991-3c4ee780-e488-11e9-865b-b549f1510dd7.png)

**Comment by EdiWang** [comment]
I change my mind and decided to leave the review switch to blog admin. Reopening this issue.

**Comment by EdiWang** [comment]
Fixed and will be in this month's release.
