### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#266]
Allow pin this to home screen.

**Comment by EdiWang** [comment]
You can already pin this using IE or Windows Phone

**Comment by Anduin2017** [comment]
manifest.json support please.

**Comment by EdiWang** [comment]
@Anduin2017 

You can now pin the website to taskbar 

![image](https://user-images.githubusercontent.com/3304703/67631751-49b79000-f8d5-11e9-8112-7c2c18266267.png)
