### ISSUE TITLE
Provide a portal to manage these settings

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#267]
![image](https://user-images.githubusercontent.com/19531547/65960181-70c1a400-e486-11e9-9db7-0a37ee5cd0ea.png)

**Comment by Anduin2017** [comment]
I may add my twitter\facebook\youtube\bilibili account here. But it seems hard to config.

**Comment by EdiWang** [comment]
As mentioned in Readme. This is a known limit currently. You can only change the HTML code for the footer.

**Comment by EdiWang** [comment]
@Anduin2017 this feature request is planned in next release.
