### ISSUE TITLE
Switchable themes

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#301]
Provide the users several themes and the user can select a preferred one.

A theme might be light style or dark style. It can change the navigation color to other ones instead of blue. (Like green)

![image](https://user-images.githubusercontent.com/19531547/70308456-43a6be80-1846-11ea-9392-ab8fef854346.png)

**Comment by EdiWang** [comment]
Will support switching accent colors recently. Dark/light support will come later.

**Comment by Anduin2017** [comment]
Released to my app service. Well done! Very cool!

![image](https://user-images.githubusercontent.com/19531547/70376719-e3e40c80-1946-11ea-8d25-1a54efa144d4.png)

**Comment by EdiWang** [comment]
Currently, dark mode is only supported in reading view via #311, site-wide dark mode is under consideration and I don't have an ETA for it.

**Comment by Anduin2017** [comment]
Cool!
