### ISSUE TITLE
Setup Error in UserTimeZoneBaseUtcOffset

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Moonglade#302]
**Describe the bug**
An invalid default settings value blow up @Anduin2017 sky high

**To Reproduce**
1. Setup a new instance of moonglade
2. Visit the website
3. Get 500 error

**Expected behavior**
Default page should be open

**Additional context**
Use this value as default to save the day:

```json
{"Ticks":288000000000,"Days":0,"Hours":8,"Milliseconds":0,"Minutes":0,"Seconds":0,"TotalDays":0.3333333333333333,"TotalHours":8,"TotalMilliseconds":28800000,"TotalMinutes":480,"TotalSeconds":28800}
```

**Comment by Anduin2017** [comment]
Nice one!
