### ISSUE TITLE
Support markdown as the editor.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#304]
I hate HTML editor. Please provide a markdown editior.

https://github.com/AiursoftWeb/Nexus/blob/master/Developer/Views/Tools/Markdown.cshtml

**Comment by EdiWang** [comment]
Nice suggestion, will plan this feature in a recent release.

**Comment by Anduin2017** [comment]
Ohhh. How is it progress?

**Comment by EdiWang** [comment]
@Anduin2017 you can check out ```md-editor``` branch for a buggy preview, it basically works, but things may blow up everywhere sky high.

**Comment by EdiWang** [comment]
To enable markdown editor:

```json
"AppSettings": {
    "Editor": "Markdown"
}
```

**Comment by Anduin2017** [comment]
Cool!
