### ISSUE TITLE
Supported blogger description is tooooo short.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#306]
![image](https://user-images.githubusercontent.com/19531547/70372497-ca2cd000-191a-11ea-8a9b-ea3ffe818c7e.png)

Supported description is too short. I want to set it to:

```
Founder of Aiursoft. I love C# and TypeScript and I'm focusing on Micro-services, DevOps, Web and PWA.
```

But it just rejected me!

**Comment by EdiWang** [comment]
Current character limit is 64, do you like to expand to 256? @Anduin2017

**Comment by Anduin2017** [comment]
Nice!

**Comment by EdiWang** [comment]
Please try the latest code @Anduin2017
