### ISSUE TITLE
Strange banner color issue.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#321]
![image](https://user-images.githubusercontent.com/19531547/71353882-48dd6a80-25b5-11ea-9df0-024b0d429af4.png)

Repro steps:

* Open Microsoft Edge Beta
* Open https://anduin.aiursoft.com
* Click `Install this site as an app`
* Click the menu several times.

**Comment by EdiWang** [comment]
It can't be reproduced on my machine. However, there is an incorrect hard-coded color for the title bar:

![image](https://user-images.githubusercontent.com/3304703/71390472-81c02280-263b-11ea-980d-cdac021d92a5.png)
