### ISSUE TITLE
Upload images for Markdown Editor

### ISSUE THREAD

**Issue by Zhuangkh** [EdiWang/Moonglade#327]
Is there a good way to insert images quickly in Markdown editor? It is too stupid to uploading Manually. (996😂)

**Comment by EdiWang** [comment]
Image upload is not supported in MD editor yet, the preferred choice is HTML editor while you can copy paste to upload image. Image upload in MD editor requires me to work 996, this will be implemented in the near future.

**Comment by EdiWang** [comment]
For reference: https://github.com/sparksuite/simplemde-markdown-editor/issues/328

**Comment by EdiWang** [comment]
Worked 996 and implemented solution, now you could upload images by CTRL + V or drag and drop:

![image](https://user-images.githubusercontent.com/3304703/72215449-9e21f180-354d-11ea-8310-8eafe018064b.png)

![image](https://user-images.githubusercontent.com/3304703/72215457-b98cfc80-354d-11ea-8029-284d8c09e1c8.png)

CC: @Anduin2017

**Comment by Anduin2017** [comment]
Cool!

**Comment by Zhuangkh** [comment]
awesome!
