### ISSUE TITLE
Concurrent file log blow up

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Moonglade#340]
**Describe the bug**
When too many threads are writing logs to a single file, Moonglade went kaboom

**To Reproduce**
1. Generate enough concurrent user load to write logs
2. At some point, the server blows up

**Expected behavior**
The server should not blow up and log loss are acceptable

**Screenshots**
![image](https://user-images.githubusercontent.com/3304703/75306462-1c2f2300-5884-11ea-85af-e3addc081a3a.png)

**Additional context**
May refer to https://github.com/NLog/NLog/issues/2750

**Comment by snakefoot** [comment]
These settings are for the FileTarget, and not the nlog-root-element:
```xml
      concurrentWrites="true"
      keepFileOpen="true"
```

Try this instead:

```xml
<?xml version="1.0"?>
<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      autoReload="true"
      internalLogLevel="Warn"
      internalLogFile="App_Data/logs/internal-nlog.txt">

  <extensions>
    <add assembly="NLog.Web.AspNetCore"/>
  </extensions>

  <targets>
    <target name="ownfile" xsi:type="File"
            fileName="${basedir}\..\..\LogFiles\Application\${shortdate}.log"
            concurrentWrites="true"
            keepFileOpen="true"
            encoding="utf-8"
            layout="${longdate}|${machinename}|${uppercase:${level}}|${logger}|${message}|${exception:format=tostring}|${aspnet-request-method}|${aspnet-traceidentifier}|${aspnet-request-ip}|${aspnet-request-url}|${aspnet-mvc-action}" />
  </targets>
  <rules>
    <!--Skip non-critical Microsoft logs and so log only own logs-->
    <logger name="Microsoft.*" maxLevel="Info" final="true" />
    <logger name="*" minlevel="Info" writeTo="ownfile" />
  </rules>
</nlog>
```

If you want to speed up the performance even further then you can replace `<targets>` with `<targets async="true">`. See also https://github.com/NLog/NLog/wiki/performance#file-logging-performance

**Comment by EdiWang** [comment]
@snakefoot Thanks for pointing out, it's really helpful.
