### ISSUE TITLE
Live ID integrated sign in to comment

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#353]
Request a feature to login via live ID (Microsoft Account) to comment.

* Which prevents spam for the blog owner.
* Which prevents spam from the blog system to target because email is always real..
* Improve Microsoft account usage.
* Safe and easy.
* Halal

**Comment by EdiWang** [comment]
This will make moonglade setup a bit harder because the users need to setup MSA keys also...
