### ISSUE TITLE
<hr> disappeared in black theme

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#368]
**Describe the bug**

![image](https://user-images.githubusercontent.com/19531547/78971870-1d1fc980-7b3f-11ea-8f27-f49790227b34.png)

**To Reproduce**

1. Go to any article detail page
2. Click on 'black theme'
3. Scroll down to 'Tags'

**Expected behavior**

![image](https://user-images.githubusercontent.com/19531547/78971988-50faef00-7b3f-11ea-97ef-cb8994f07c26.png)

**Screenshots**

![image](https://user-images.githubusercontent.com/19531547/78971899-29a42200-7b3f-11ea-97fc-b9c07bc266ea.png)

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Browser [New Edge]
 - Version [e.g. 80]

**Additional context**

**Comment by EdiWang** [comment]
😂
