### ISSUE TITLE
The switch theme button might be unclickable in some resolutions.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#370]
![image](https://user-images.githubusercontent.com/19531547/78972174-b7800d00-7b3f-11ea-953f-c50ba79334bc.png)

When I click this button, nothing happened.

Resolution: 1195*796

**Comment by EdiWang** [comment]
Thanks for reporting this issue, I'll work 996 to fix it.

**Comment by EdiWang** [comment]
This issue is the same root cause with #369
