### ISSUE TITLE
Feature request: Create custom dropdown menu in the navigation bar.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#411]
![image](https://user-images.githubusercontent.com/19531547/80912159-a2c51c80-8d6d-11ea-80e2-50c6158a8eea.png)

Now I have a customized navigation menu called `Channel`. And it is fixed with only one URL available.

I want to set it as a drop-down menu, so the viewer can check the detailed more options under it.

**Comment by EdiWang** [comment]
Usually, this is a blog, not a CMS, it shouldn't have a rich menu editing experience. However, WordPress started from a blog and then made it's way to CMS, I don't know if Moonglade should do the same. So this feature request would be under consideration for now.

**Comment by Anduin2017** [comment]
OK. Or create an advanced editor to edit the navbar as HTML.

**Comment by EdiWang** [comment]
Initial support will be in version 11.3
