### ISSUE TITLE
filesystem provider for ImageStorage breaks in docker

### ISSUE THREAD

**Issue by iwenli** [EdiWang/Moonglade#412]
ImageStorage 使用 filesystem 时，在Dokcer中不能正常运行.
问题出现原因是 AppSettings.Json 文件中 FileSystemSettings.Path 路径是写死的 `\\`

应该是这句导致的，可以换下写法 `path.Replace(basedirStr, contentRootPath)`

---

**Translated**

When setting filesystem as ImageStorage, it can't run correctly under Docker.

The problem is FileSystemSettings.Path in AppSettings.json being hard coded as `\\`

It may be caused by this line of code `path.Replace(basedirStr, contentRootPath)`

**Comment by EdiWang** [comment]
It is recommended to use Environment Variables over appsetting.json file for hosting Moonglade. Thus, you can workaround this issue by setting ```ImageStorage__FileSystemSettings__Path``` to a Linux path like ```/some/folder```

Still, I am going to modify my code to make the default settings compatible across Windows and Linux.
