### ISSUE TITLE
Legal question

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Moonglade#461]
I just successfully deploy your code onto my own azure web app service https://manaatmoonblog.azurewebsites.net/.  Since i don't know if there is any legal requirement, so please let me know if i need to obey any rules.

_Originally posted by @manaatmoon in https://github.com/EdiWang/Moonglade/issues/300#issuecomment-652152812_

**Comment by EdiWang** [comment]
Hi @manaatmoon 

There isn't any legal requirements so far as long as you keep the "Moonglade xxxxx, Developed by Edi Wang" in the footer copyright section. You can modify other part of the system.

BTW, your 'About' page is not working. This is probably because you use the code from master branch and missing a few SQL migration that hasn't been written to release note yet. 

For a stable version, please use code from Release page https://github.com/EdiWang/Moonglade/releases

**Comment by Anduin2017** [comment]
As the project is under GPL, please apply all requirements from GPL license: 

https://en.wikipedia.org/wiki/GNU_General_Public_License

And you'd better declare the license under all your posts. Without declaring license for your posts, it represents that `all rights reserved to you`.

If you forked this project or edited it, you **MUST** make the whole project open source.

**Comment by EdiWang** [comment]
The content of the posts are copyrighted for the users, it's user data, so it's fine not to declare license under posts. 

But since Moonglade code is under GPL, so yes, if you forked and modified the code, it need to go open source as well.

**Comment by manaatmoon** [comment]
@EdiWang, @Anduin2017  Thanks a lot.
