### ISSUE TITLE
Friend links cannot be added

### ISSUE THREAD

**Issue by Lesliewxj** [EdiWang/Moonglade#490]
**Describe the bug**
friend links can not be added in the back end.

**To Reproduce**
1. Go to 'blog admin page'
2. Click on 'Settings'
3. Click on 'Friend Links' to add a new friend link.
4. Go to the home page.
4. See error.

**Environment :**
 - OS: Windows 10
 - Browser Chrome
 - Version 70

**Additional context**
Only the link that was initialized can be displayed

**Comment by EdiWang** [comment]
Cannot reproduce, works fine both on local and production. Friendlink cache has 60 minutes expiration time, please wait until the cache update, or you can just restart the application to force cache update.

**Comment by Lesliewxj** [comment]
60 minutes, I got it! Thanks a lot.
