### ISSUE TITLE
captcha is abnormal on centos

### ISSUE THREAD

**Issue by Aprite** [EdiWang/Moonglade#508]
hi, 大神.
Captcha Code is abnormal.

Go to 'Post/Slug.cshtml'

 - OS: [e.g. CentOS 8]
 - Browser [e.g. Chrome]
 - Version [e.g. 80]

**Additional context**
GetCaptchaImage is use ISessionBasedCaptcha in Edi.Captcha.dll
maybe it not work on CentOS

thinks.

**Comment by Aprite** [comment]
PS H:\gogs.aprite.cn\Moonglade\src\Moonglade.Web> dotnet build --no-incremental --no-restore --runtime linux-x64 --configuration Release .\Moonglade.Web.csproj
Microsoft (R) Build Engine version 16.8.0+126527ff1 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.


  Bundler: Cleaning output from bundleconfig.json
  Bundler: Done cleaning output file from bundleconfig.json
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1047: Assets file 'H:\gogs.aprite.cn\Moonglade\src\Moonglade.Web\obj\project.assets.json' doesn't have a target for 'net5.0/linux-x64'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. You may also need to include 'linux-x64' in your project's RuntimeIdentifiers. [H:\gogs.aprite.cn\Moonglade\src\Moonglade.Web\Moonglade.Web.csproj]

Build FAILED.

C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(241,5): error NETSDK1047: Assets file 'H:\gogs.aprite.cn\Moonglade\src\Moonglade.Web\obj\project.assets.json' doesn't have a target for 'net5.0/linux-x64'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project. You may also need to include 'linux-x64' in your project's RuntimeIdentifiers. [H:\gogs.aprite.cn\Moonglade\src\Moonglade.Web\Moonglade.Web.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.78

**Comment by EdiWang** [comment]
For captcha code, have you installed `libgdiplus`?

I don't have CentOS environment, on Ubuntu it can be installed via `apt`

`bash
sudo apt-get update && sudo apt-get install -y libgdiplus
`

For the build issue, it's wired because my build on docker works fine, it's also Linux X64 and I don't have MySQL dependencies.

**Comment by EdiWang** [comment]
Please try to clean the source directory (delete `/bin` `/obj` `/debug` folder) and rebuild the solution. Or you can just clone the source code to a new directory. This may be caused by outdated build cache.

**Comment by Aprite** [comment]
@EdiWang  thank you very much 
on centos  
`yum install libgdiplus`
it works
