### ISSUE TITLE
Support open graph meta data.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#533]
For example, if I share a link to Twitter, it will have an incredibly beautiful rendering. Like this:

![image](https://user-images.githubusercontent.com/19531547/113312236-aaee5900-933c-11eb-9902-c8c33a7800b0.png)

But if I paste a moonglade URL. It's just like this:

![image](https://user-images.githubusercontent.com/19531547/113312317-c194b000-933c-11eb-9646-6db745d5fcc2.png)

This causes Moonglade users unhappy to forward their posts on social medias, like SharePoint, Twitter and FaceBook.

To support that, please reference the open graph meta data.

https://ogp.me/

![image](https://user-images.githubusercontent.com/19531547/113312476-e9841380-933c-11eb-8488-30957bd306ac.png)

For example, this is mata data from http://dot.net

```xml
<meta property="og:title" content=".NET \| Free. Cross-platform. Open Source." />
<meta property="og:description" content=".NET is a developer platform with tools and libraries for building any type of app, including web, mobile, desktop, games, IoT, cloud, and microservices." />
<meta property="og:image" content="https://dotnet.microsoft.com/static/images/redesign/social/square.png" />
<meta property="og:image:secure_url" content="https://dotnet.microsoft.com/static/images/redesign/social/square.png" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Microsoft" />
```

**Comment by Anduin2017** [comment]
This is also best practice for SEO.

**Comment by EdiWang** [comment]
It's already implemented long long ago, you just need to enable the open graph switch in admin settings.

![image](https://user-images.githubusercontent.com/3304703/113369857-f896b000-9394-11eb-9b84-e0b8d1fa8747.png)

![image](https://user-images.githubusercontent.com/3304703/113369834-e74da380-9394-11eb-841e-4b643600f59c.png)

**Comment by Anduin2017** [comment]
Wow. Cool.

By the way, why not enable this by default?

**Comment by EdiWang** [comment]
Because of some curry reason
