### ISSUE TITLE
Strange front-end effect.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#546]
**Describe the bug**

Happens with my version: `11.4-Preview2 (3f83eb)`

**To Reproduce**
1. Go to moonglade home.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/19531547/117538204-ae5dba00-b037-11eb-9cd6-fe9236d7e515.png)

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser: Edge
 - Version [e.g. 70]

**Additional context**

**Comment by EdiWang** [comment]
This is because Moonglade is using Bootstrap 5.0 with Bootstrap Icons instead of moonglade icons. You have to work 996 and learn bootstrap 5.0 then migrate your customized HTML and CSS to 5.0.

**Comment by EdiWang** [comment]
Check https://getbootstrap.com/docs/5.0/migration/ or just copy HTML code from my blog

**Comment by Anduin2017** [comment]
Got it.

Custom css:

```css
.blog-info-desktop-lg {
    border-radius: 3px 3px 0 0
}

.btn-profile-about {
    border-radius: 0 0 3px 3px;
}

```

And HTML:

```html
<div class="btn-group w-100 mb-3" role="group" aria-label="profile-buttons">
  <a class="btn btn-success btn-profile-about" href="/page/about">About</a>
  <a class="btn btn-primary btn-profile-about" href="https://github.com/Anduin2017" target="_blank">GitHub</a>
</div>
```
