### ISSUE TITLE
The "curl -sL ifconfig.me" in the installation script cannot obtain the external IP address of the Linux server.

### ISSUE THREAD

**Issue by Lesliewxj** [EdiWang/Moonglade#571]
Ubuntu server version is 18.04,The "curl -sL ifconfig.me" in the script cannot obtain the external IP address of the Linux server. I suggest changing it to "curl -s icanhazip.com" to get.
https://raw.githubusercontent.com/Lesliewxj/lesliewxj-image/master/git-issue/install.368k8h6q83o0.png

**Comment by Anduin2017** [comment]
Hi. Thanks for your feedback.

Any other context which helps us investigate?

**Comment by Lesliewxj** [comment]
Hello, I can successfully install by changing "ipconfig.me" to "icanhazip.com". As for the difference between the two, I haven't delved into it yet, because I have seen the Internet saying that it is possible to obtain the external IP address in this way , So I gave it a try. The changes are as follows:
https://raw.githubusercontent.com/Lesliewxj/lesliewxj-image/master/git-issue/install01.4u48fyqdzt60.png

In addition, when I installed some other problems, whether to install mssql and other services separately.
https://raw.githubusercontent.com/Lesliewxj/lesliewxj-image/master/git-issue/install02.47kw2xbay500.png

After changing "ipconfig.me" to "icanhazip.com", the complete log of the installation is as follows:
Installing Moonglade to domain ...
IP is correct.
Using internal port: 127.0.0.1:57966 to run the internal service.
Installing git vim dotnet-sdk caddy mssql-server mssql-tools nodejs ufw libgdiplus...
--2021-08-07 22:07:50--  https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.75.64.135
Connecting to packages.microsoft.com (packages.microsoft.com)|13.75.64.135|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3132 (3.1K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft-prod.deb                                         100%[=================================================================================================================================================================>]   3.06K  --.-KB/s    in 0s

2021-08-07 22:07:50 (517 MB/s) - ‘packages-microsoft-prod.deb’ saved [3132/3132]

Warning: apt-key output should not be parsed (stdout is not a terminal)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   103  100   103    0     0    620      0 --:--:-- --:--:-- --:--:--   620
./install.sh: line 104: add-apt-repository: command not found

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Unable to locate package mssql-server
./install.sh: line 152: /opt/mssql/bin/mssql-conf: No such file or directory
Failed to restart mssql-server.service: Unit mssql-server.service not found.
mkdir: cannot create directory ‘Storage’: File exists
./install.sh: line 159: git: command not found
Building the source code...
./install.sh: line 165: dotnet: command not found
./install.sh: line 167: /root/apps/moongladeApp/appsettings.Production.json: No such file or directory
Generating default configuration file...
grep: /root/apps/moongladeApp/appsettings.Production.json: No such file or directory
sed: can't read /root/apps/moongladeApp/appsettings.Production.json: No such file or directory
grep: /root/apps/moongladeApp/appsettings.Production.json: No such file or directory
sed: can't read /root/apps/moongladeApp/appsettings.Production.json: No such file or directory
./install.sh: line 174: npm: command not found
Creating database...
./install.sh: line 179: /opt/mssql-tools/bin/sqlcmd: No such file or directory
Registering Moonglade service...
Configuring the web proxy...
cat: /etc/caddy/Caddyfile: No such file or directory
./install.sh: line 62: /etc/caddy/Caddyfile: No such file or directory
Failed to restart caddy.service: Unit caddy.service not found.
Configuring the firewall...
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall reloaded
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall reloaded
Skipping adding existing rule
Skipping adding existing rule (v6)
Firewall reloaded
Command may disrupt existing ssh connections. Proceed with operation (y|n)? Firewall is active and enabled on system startup
Firewall enabled!
Status: active

To                         Action      From
--                         ------      ----
443/tcp                    ALLOW       Anywhere
80/tcp                     ALLOW       Anywhere
22/tcp                     ALLOW       Anywhere
443/tcp (v6)               ALLOW       Anywhere (v6)
80/tcp (v6)                ALLOW       Anywhere (v6)
22/tcp (v6)                ALLOW       Anywhere (v6)

Successfully installed Moonglade as a service in your machine! Please open  to try it now!
./install.sh: line 200: admin: command not found
./install.sh: line 200: admin123: command not found
Default management user name is  and default password is . Please open  to try it now!
Successfully installed mssql as a service in your machine! The port is not opened so you can't connect!
Successfully installed caddy as a service in your machine!
You can open your database to public via: sudo ufw allow 1433/tcp
You can access your database via:  with username: and password: 
Your database data file is located at: /var/opt/mssql/. Please back up them regularly.
Your web data file is located at: /root/apps/moongladeApp
Your web server config file is located at: /etc/caddy/Caddyfile
Strongly maintain your own configuration at /root/apps/moongladeApp/appsettings.Production.json
Strongly suggest run 'sudo apt upgrade' and reboot when convience!

**Comment by Anduin2017** [comment]
Hi. Thanks for the feedback! It seems to be more than one issue.

Will fix in the next days.

**Comment by Anduin2017** [comment]
Hi. Just did a test. Here is the output on our side (Installed successfully):

<div style="display:inline-block;white-space:pre;background-color:#2C001E;font-family:'Cascadia Code',monospace;font-size:12pt;padding:4px;"><span style="color:#53E14E;background-color:#2C001E;">FAREAST+xuef@DESK-HOMEWORK&nbsp;</span><span style="color:#A837B8;background-color:#2C001E;">MINGW64&nbsp;</span><span style="color:#E1AC10;background-color:#2C001E;">~<br></span><span style="color:#EEEEEC;background-color:#2C001E;">$ ssh root@45.76.146.163<br>The authenticity of host &apos;45.76.146.163 (45.76.146.163)&apos; can&apos;t be established.<br>ED25519 key fingerprint is SHA256:i/aXnZqGAgMoQc2YGkBZH9pwIPWUSgttnKGoC2ihnNM.<br>This key is not known by any other names<br>Are you sure you want to continue connecting (yes/no/[fingerprint])? yes<br>Warning: Permanently added &apos;45.76.146.163&apos; (ED25519) to the list of known hosts.<br>Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-143-generic x86_64)<br><br>&nbsp;* Documentation: &nbsp;https://help.ubuntu.com<br>&nbsp;* Management: &nbsp; &nbsp; https://landscape.canonical.com<br>&nbsp;* Support: &nbsp; &nbsp; &nbsp; &nbsp;https://ubuntu.com/advantage<br><br>&nbsp; System information as of Mon Aug &nbsp;9 06:57:28 UTC 2021<br><br>&nbsp; System load: &nbsp;0.0 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Processes: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 90<br>&nbsp; Usage of /: &nbsp; 4.7% of 51.57GB &nbsp; Users logged in: &nbsp; &nbsp; &nbsp; 0<br>&nbsp; Memory usage: 6% &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;IP address for enp1s0: 45.76.146.163<br>&nbsp; Swap usage: &nbsp; 0%<br><br><br>54 updates can be applied immediately.<br>31 of these updates are standard security updates.<br>To see these additional updates run: apt list --upgradable<br><br><br>root@TestMoon:~# curl -sL https://go.edi.wang/aka/mgli | sudo bash -s testmoon.anduinxue.com<br>Installing Moonglade to domain testmoon.anduinxue.com...<br>IP is correct.<br>Using internal port: 127.0.0.1:58032 to run the internal service.<br>ASPNETCORE_ENVIRONMENT=&quot;Production&quot;<br>DOTNET_CLI_TELEMETRY_OPTOUT=&quot;1&quot;<br>DOTNET_PRINT_TELEMETRY_MESSAGE=&quot;false&quot;<br>ASPNETCORE_FORWARDEDHEADERS_ENABLED=&quot;true&quot;<br>Installing git vim dotnet-sdk caddy mssql-server mssql-tools nodejs ufw libgdiplus...<br>--2021-08-09 06:57:51-- &nbsp;https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb<br>Resolving packages.microsoft.com (packages.microsoft.com)... 52.230.121.169<br>Connecting to packages.microsoft.com (packages.microsoft.com)|52.230.121.169|:443... connected.<br>HTTP request sent, awaiting response... 200 OK<br>Length: 3132 (3.1K) [application/octet-stream]<br>Saving to: &lsquo;packages-microsoft-prod.deb&rsquo;<br><br>packages-microsoft-prod.deb &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;100%[=========================================================================&gt;] &nbsp; 3.06K &nbsp;--.-KB/s &nbsp; &nbsp;in 0s<br><br>2021-08-09 06:57:51 (277 MB/s) - &lsquo;packages-microsoft-prod.deb&rsquo; saved [3132/3132]<br><br>cat: /etc/apt/sources.list.d/caddy-fury.list: No such file or directory<br>Warning: apt-key output should not be parsed (stdout is not a terminal)<br>&nbsp; % Total &nbsp; &nbsp;% Received % Xferd &nbsp;Average Speed &nbsp; Time &nbsp; &nbsp;Time &nbsp; &nbsp; Time &nbsp;Current<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Dload &nbsp;Upload &nbsp; Total &nbsp; Spent &nbsp; &nbsp;Left &nbsp;Speed<br>100 &nbsp; 103 &nbsp;100 &nbsp; 103 &nbsp; &nbsp;0 &nbsp; &nbsp; 0 &nbsp; 3433 &nbsp; &nbsp; &nbsp;0 --:--:-- --:--:-- --:--:-- &nbsp;3433<br><br>WARNING: apt does not have a stable CLI interface. Use with caution in scripts.<br><br>Extracting templates from packages: 100%<br>usermod: no changes<br>The license terms for this product can be found in<br>/usr/share/doc/mssql-server or downloaded from:<br>https://go.microsoft.com/fwlink/?LinkId=2104294&amp;clcid=0x409<br><br>The privacy statement can be viewed at:<br>https://go.microsoft.com/fwlink/?LinkId=853010&amp;clcid=0x409<br><br>Configuring SQL Server...<br><br>The licensing PID was successfully processed. The new edition is [Express Edition].<br>ForceFlush is enabled for this instance.<br>ForceFlush feature is enabled for log durability.<br>Created symlink /etc/systemd/system/multi-user.target.wants/mssql-server.service &rarr; /lib/systemd/system/mssql-server.service.<br>Setup has completed successfully. SQL Server is now starting.<br>Cloning into &apos;Moonglade&apos;...<br>remote: Enumerating objects: 39828, done.<br>remote: Counting objects: 100% (12461/12461), done.<br>remote: Compressing objects: 100% (3396/3396), done.<br>remote: Total 39828 (delta 9895), reused 11511 (delta 8975), pack-reused 27367<br>Receiving objects: 100% (39828/39828), 13.18 MiB | 8.48 MiB/s, done.<br>Resolving deltas: 100% (31379/31379), done.<br>Building the source code...<br><br>Welcome to .NET 5.0!<br>---------------------<br>SDK Version: 5.0.302<br><br>----------------<br>Installed an ASP.NET Core HTTPS development certificate.<br>To trust the certificate run &apos;dotnet dev-certs https --trust&apos; (Windows and macOS only).<br>Learn about HTTPS: https://aka.ms/dotnet-https<br>----------------<br>Write your first app: https://aka.ms/dotnet-hello-world<br>Find out what&apos;s new: https://aka.ms/dotnet-whats-new<br>Explore documentation: https://aka.ms/dotnet-docs<br>Report issues and find source on GitHub: https://github.com/dotnet/core<br>Use &apos;dotnet --help&apos; to see available commands or visit: https://aka.ms/dotnet-cli<br>--------------------------------------------------------------------------------------<br>Microsoft (R) Build Engine version 16.10.2+857e5a733 for .NET<br>Copyright (C) Microsoft Corporation. All rights reserved.<br><br>&nbsp; Determining projects to restore...<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Web/Moonglade.Web.csproj (in 3.07 min).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Utils/Moonglade.Utils.csproj (in 13 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Theme/Moonglade.Theme.csproj (in 221 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Syndication/Moonglade.Syndication.csproj (in 144 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Pingback/Moonglade.Pingback.csproj (in 114 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Notification.Client/Moonglade.Notification.Client.csproj (in 54 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Menus/Moonglade.Menus.csproj (in 123 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.ImageStorage/Moonglade.ImageStorage.csproj (in 25 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.FriendLink/Moonglade.FriendLink.csproj (in 137 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Data/Moonglade.Data.csproj (in 1.72 sec).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Core/Moonglade.Core.csproj (in 137 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Configuration/Moonglade.Configuration.csproj (in 34 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Comments/Moonglade.Comments.csproj (in 173 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Caching/Moonglade.Caching.csproj (in 4 ms).<br>&nbsp; Restored /root/Moonglade/src/Moonglade.Auth/Moonglade.Auth.csproj (in 166 ms).<br><br>&nbsp; Restore operation started...<br><br>&nbsp; 10 libraries restored in 45.02 seconds<br><br>&nbsp; Moonglade.Data -&gt; /root/Moonglade/src/Moonglade.Data/bin/Release/net5.0/Moonglade.Data.dll<br>&nbsp; Moonglade.Utils -&gt; /root/Moonglade/src/Moonglade.Utils/bin/Release/net5.0/Moonglade.Utils.dll<br>&nbsp; Moonglade.Auth -&gt; /root/Moonglade/src/Moonglade.Auth/bin/Release/net5.0/Moonglade.Auth.dll<br>&nbsp; Moonglade.Configuration -&gt; /root/Moonglade/src/Moonglade.Configuration/bin/Release/net5.0/Moonglade.Configuration.dll<br>&nbsp; Moonglade.Comments -&gt; /root/Moonglade/src/Moonglade.Comments/bin/Release/net5.0/Moonglade.Comments.dll<br>&nbsp; Moonglade.Caching -&gt; /root/Moonglade/src/Moonglade.Caching/bin/Release/net5.0/Moonglade.Caching.dll<br>&nbsp; Moonglade.Core -&gt; /root/Moonglade/src/Moonglade.Core/bin/Release/net5.0/Moonglade.Core.dll<br>&nbsp; Moonglade.FriendLink -&gt; /root/Moonglade/src/Moonglade.FriendLink/bin/Release/net5.0/Moonglade.FriendLink.dll<br>&nbsp; Moonglade.ImageStorage -&gt; /root/Moonglade/src/Moonglade.ImageStorage/bin/Release/net5.0/Moonglade.ImageStorage.dll<br>&nbsp; Moonglade.Menus -&gt; /root/Moonglade/src/Moonglade.Menus/bin/Release/net5.0/Moonglade.Menus.dll<br>&nbsp; Moonglade.Notification.Client -&gt; /root/Moonglade/src/Moonglade.Notification.Client/bin/Release/net5.0/Moonglade.Notification.Client.dll<br>&nbsp; Moonglade.Pingback -&gt; /root/Moonglade/src/Moonglade.Pingback/bin/Release/net5.0/Moonglade.Pingback.dll<br>&nbsp; Moonglade.Syndication -&gt; /root/Moonglade/src/Moonglade.Syndication/bin/Release/net5.0/Moonglade.Syndication.dll<br>&nbsp; Moonglade.Theme -&gt; /root/Moonglade/src/Moonglade.Theme/bin/Release/net5.0/Moonglade.Theme.dll<br><br>&nbsp; Bundler: Begin processing bundleconfig.json<br>&nbsp; &nbsp; &nbsp; &nbsp; Bundled wwwroot/css/tinymce-bs-bundle.css<br>&nbsp; &nbsp; &nbsp; &nbsp; Minified wwwroot/css/tinymce-bs-bundle.min.css<br>&nbsp; &nbsp; &nbsp; &nbsp; Bundled wwwroot/js/dist/app-bundle.js<br>&nbsp; &nbsp; &nbsp; &nbsp; Minified wwwroot/js/dist/app-bundle.min.js<br>&nbsp; &nbsp; &nbsp; &nbsp; Bundled wwwroot/js/dist/admin-bundle.js<br>&nbsp; &nbsp; &nbsp; &nbsp; Minified wwwroot/js/dist/admin-bundle.min.js<br>&nbsp; &nbsp; &nbsp; &nbsp; Bundled wwwroot/css/bundle.css<br>&nbsp; &nbsp; &nbsp; &nbsp; Minified wwwroot/css/bundle.min.css<br>&nbsp; &nbsp; &nbsp; &nbsp; Bundled wwwroot/css/admin-bundle.css<br>&nbsp; &nbsp; &nbsp; &nbsp; Minified wwwroot/css/admin-bundle.min.css<br>&nbsp; Bundler: Done processing bundleconfig.json<br>&nbsp; Moonglade.Web -&gt; /root/Moonglade/src/Moonglade.Web/bin/Release/net5.0/linux-x64/Moonglade.Web.dll<br>&nbsp; Moonglade.Web -&gt; /root/Moonglade/src/Moonglade.Web/bin/Release/net5.0/linux-x64/Moonglade.Web.Views.dll<br>&nbsp; Some ReadyToRun compilations emitted warnings, indicating potential missing dependencies. Missing dependencies could potentially cause runtime failures. To show the warnings, set the PublishReadyToRunShowWarn<br>ings property to true.<br>&nbsp; Moonglade.Web -&gt; /root/apps/moongladeApp/<br>Generating default configuration file...<br>/usr/bin/web-push -&gt; /usr/lib/node_modules/web-push/src/cli.js<br>+ web-push@3.4.5<br>added 18 packages from 17 contributors in 3.76s<br>Creating database...<br>Registering Moonglade service...<br>Created symlink /etc/systemd/system/multi-user.target.wants/moonglade.service &rarr; /etc/systemd/system/moonglade.service.<br>Configuring the web proxy...<br>Configuring the firewall...<br>Rules updated<br>Rules updated (v6)<br>Firewall not enabled (skipping reload)<br>Rules updated<br>Rules updated (v6)<br>Firewall not enabled (skipping reload)<br>Rules updated<br>Rules updated (v6)<br>Firewall not enabled (skipping reload)<br>Command may disrupt existing ssh connections. Proceed with operation (y|n)? Firewall is active and enabled on system startup<br>Firewall enabled!<br>Status: active<br><br>To &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Action &nbsp; &nbsp; &nbsp;From<br>-- &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ------ &nbsp; &nbsp; &nbsp;----<br>443/tcp &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ALLOW &nbsp; &nbsp; &nbsp; Anywhere<br>80/tcp &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ALLOW &nbsp; &nbsp; &nbsp; Anywhere<br>22/tcp &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ALLOW &nbsp; &nbsp; &nbsp; Anywhere<br>443/tcp (v6) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ALLOW &nbsp; &nbsp; &nbsp; Anywhere (v6)<br>80/tcp (v6) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ALLOW &nbsp; &nbsp; &nbsp; Anywhere (v6)<br>22/tcp (v6) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;ALLOW &nbsp; &nbsp; &nbsp; Anywhere (v6)<br><br>Successfully installed Moonglade as a service in your machine! Please open https://testmoon.anduinxue.com to try it now!<br>main: line 201: admin: command not found<br>main: line 201: admin123: command not found<br>Default management user name is &nbsp;and default password is . Please open https://testmoon.anduinxue.com/admin to try it now!<br>Successfully installed mssql as a service in your machine! The port is not opened so you can&apos;t connect!<br>Successfully installed caddy as a service in your machine!<br>You can open your database to public via: sudo ufw allow 1433/tcp<br>You can access your database via: testmoon.anduinxue.com:1433 with username: sa and password: 0e34358a-bb1f-41a2-95bf-1e59e4998b54<br>Your database data file is located at: /var/opt/mssql/. Please back up them regularly.<br>Your web data file is located at: /root/apps/moongladeApp<br>Your web server config file is located at: /etc/caddy/Caddyfile<br>Strongly maintain your own configuration at /root/apps/moongladeApp/appsettings.Production.json<br>Strongly suggest run &apos;sudo apt upgrade&apos; and reboot when convience!<br>root@TestMoon:~#</span></div>

**Comment by Anduin2017** [comment]
From your output, it seems not to be a bug on our side. Since our scripts works fine.

And your error message is: 

```bash
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

E: Unable to locate package mssql-server
```

It is highly possible that might be Internet issue, or wrong OS version.

Don't forget!!!:

Get a brand new Ubuntu 18.04 server.

Server must be Ubuntu 18.04. (20.04 and 16.04 is not supported)
Server must have a public IP address. (No local VM)
Server must have access to the global Internet. (Not Chinese network)
Vultr or DigitalOcean is recommended besides Azure.

**Comment by Lesliewxj** [comment]
I tried it again, and it was indeed a problem with my network. Although I installed the tool for accessing the Internet, it did not start. Thank you very much.
