### ISSUE TITLE
An Error occured while starting the application

### ISSUE THREAD

**Issue by BionStt** [EdiWang/Moonglade#579]
Hai Edi,
I got some error after publishing to azure. 

![moonglade error](https://user-images.githubusercontent.com/43228630/135560816-7c5fae92-3933-42d9-83b3-851e3050c703.jpg)

please give me some advice to resolve this problem.
thank you.

**Comment by EdiWang** [comment]
Seems you are using the default connection string in appsettings.json. Please create a new Azure SQL Database and apply it's connection string in Azure App Service's configuration tab.

**Comment by BionStt** [comment]
yes. everthing done after i deleted this code 

//if (Environment.GetEnvironmentVariable("ASPNETCORE_ENVIRONMENT") == "Production")
            //{
            //    services.AddTransient<IDbConnection>(db => new SqlConnection(_configuration.GetConnectionString("AzureAppConfig")));

            //    services.AddDataStorage(_configuration.GetConnectionString("AzureAppConfig"))
            //            .AddAuditStorage(_configuration.GetConnectionString("AzureAppConfig")) //audit
            //              .AddAuthStorage(_configuration.GetConnectionString("AzureAppConfig")); //auth db

            //}
            //else
            //{
            //    services.AddTransient<IDbConnection>(db => new SqlConnection(_configuration.GetConnectionString("AzureAppConfig")));

            //    services.AddDataStorage(_configuration.GetConnectionString("MoongladeDatabase"))
            //           .AddAuditStorage(_configuration.GetConnectionString("MoongladeDatabase")) //audit
            //             .AddAuthStorage(_configuration.GetConnectionString("MoongladeDatabase")); //auth db
            //}
