### ISSUE TITLE
Crash when saving posts.

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#585]
When I wrote a post, and I just click save, this error appears:

![4b6f797daab6bcebf3b66ada3b746bd](https://user-images.githubusercontent.com/19531547/140256951-6b6e686c-ef45-443f-9887-02e2286ae57f.png)

![fa69d33ce03bb57df6cef89cb8ba2d4](https://user-images.githubusercontent.com/19531547/140256993-d0b5d3b1-c82b-49e1-8cfd-d702c6677ab3.png)

![209e221339c8b60918751e586952383](https://user-images.githubusercontent.com/19531547/140257004-c089c014-ea8e-43ed-bcb0-7792fa065f1b.png)

An error occurred while saving the entity changes. See the inner exception for details. Cannot insert the value NULL into column 'ExposedToSiteMap', table 'anduinblogdb.dbo.Post'; column does not allow nulls. INSERT fails.
The statement has been terminated. 

![image](https://user-images.githubusercontent.com/19531547/140257029-783fce35-d106-4467-8e7c-eec01b2fb0cb.png)

**Comment by Anduin2017** [comment]
Might be related with this commit:

https://github.com/EdiWang/Moonglade/commit/d678bbdc10b2fd8ccd3a20402b3ee7dc28f5f059

**Comment by EdiWang** [comment]
Run this

```tsql
ALTER TABLE Post DROP COLUMN ExposedToSiteMap
```
