### ISSUE TITLE
Research: Git rid of Dapper and use only EF Core

### ISSUE THREAD

**Issue by EdiWang** [EdiWang/Moonglade#610]
investigate if it's possible to rewrite blog configuration and first run setup using EF Core instead of Dapper

**Comment by zhiyongpeng** [comment]
Of course, especially EF Core's code first, which does not need database scripts but directly uses entities to generate different databases, and it is easier first run setup by `seed`.

**Comment by EdiWang** [comment]
The problem with EF code first is that the generated database script is not manageable and would not be compatible when upgrading from old versions of Moonglade. There are cases where multiple Moonglade blog instances will merge there database, the SQL schema must be exactly the same. So the setup script should be kept for now.

**Comment by zhiyongpeng** [comment]
If you want to consider compatibility with old versions of Moonglade, there is no doubt that the setup script is the better way. But you can also provide a special upgrade tool for the old version of Moonglade to solve the upgrade compatibility problem.
The above is my personal opinion and is for reference only.

**Comment by zhiyongpeng** [comment]
On the other hand, I still think Dapper is good, especially when querying data (using SQL scripts directly), it is very efficient. But when Moonglade has multiple databases, different query SQL scripts need to be adapted for different databases.
