### ISSUE TITLE
User changes to blog content are lost

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#635]
**Describe the bug**

User changes to blog content are lost.

用户对于已经发布的文章内容的编辑会在保存后丢失

**To Reproduce**
1. Edit any post.
2. Save.
3. Go back to the post
4. It lost the edited content.

**Expected behavior**

After editing, it should show edited content.

**Screenshots**

https://anduins-site.player.aiur.site/moonbug2.mp4

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome]
 - Version [e.g. 70]

**Additional context**

**Comment by EdiWang** [comment]
Hi @Anduin2017 

There is a workaround:

Click "save" 3 times, it is likely to save the changes to the post content.
