### ISSUE TITLE
Found packages with vulnerabilities

### ISSUE THREAD

**Issue by Anduin2017** [EdiWang/Moonglade#640]
https://github.com/EdiWang/Moonglade/blob/54b4a0486a3c6b618a8a0a242a21c7bb0894807a/src/Moonglade.Auth/Moonglade.Auth.csproj#L19

https://github.com/EdiWang/Moonglade/blob/5068cfedffc55d6aa731904c6796185b28b83a35/src/Moonglade.Web/Moonglade.Web.csproj#L48

It is reported that .NET [6.0.5](https://dotnet.microsoft.com/download/dotnet/6.0), [5.0.17](https://dotnet.microsoft.com/download/dotnet/5.0) and, [3.1.25](https://dotnet.microsoft.com/download/dotnet/3.1) fixed several vulnerabilities.

See here:

https://devblogs.microsoft.com/dotnet/may-2022-updates/

You may get an update today:

![image](https://user-images.githubusercontent.com/19531547/167782907-f39ce770-aea5-4a81-a125-c567be0cd9b2.png)

**Comment by EdiWang** [comment]
close as fixed

**Comment by EdiWang** [comment]
It's fixed https://github.com/EdiWang/Moonglade/commit/b16e54ddab0ac3329f66920ce7557d07d3e364b7 which is in 12.1.5
