### ISSUE TITLE
Server blow up sky high when access /admin/settings/general

### ISSUE THREAD

**Issue by FunJoo** [EdiWang/Moonglade#643]
**Environment**
CentOS-7
Nginx+Kestrel
.Net 6
Moonglade version: 12.1.6

**Description**
1 - Captcha image can't load when access /admin, http code 500
Reason: CentOS has no Arial font
Resolvent: Install Arial font in CentOS7

2 - When access /admin/settings/general, “Server blow up sky high” page appears
Error:
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.TimeZoneNotFoundException: The time zone ID 'China Standard Time' was not found on the local computer.
       ---> System.IO.FileNotFoundException: Could not find file '/usr/share/zoneinfo/China Standard Time'.
Reason: Windows and CentOS have different time zone settings
Resolvent: In CentOS /usr/share/zoneinfo directory, copy PRC file and rename as "China Standard Time"..

**Comment by EdiWang** [comment]
Recommend to use docker image https://hub.docker.com/r/ediwang/moonglade for hosting moonglade on Linux. It won't have font and time zone issue.
