### ISSUE TITLE
Published post number from api don't match db value

### ISSUE THREAD

**Issue by lrxtom2** [EdiWang/Moonglade#644]
**Describe the bug**
Purpose to draft some posts, so after manually change the data from db that update some post 'isPublished' to 0, the isPublished post count number of db query doesn't match it from api(_/api/post/list/published_) value.

**To Reproduce**
1. Login to the system
2. F12 to network
3. Refresh post list
4. Manually query database

**Expected behavior**
Published post number from api should be match db value

**Screenshots**
![image](https://user-images.githubusercontent.com/20538091/172212530-e5b065f3-c8ad-4bfb-baff-fa410d8217f5.png)
![image](https://user-images.githubusercontent.com/20538091/172212657-c2558048-5d9b-4469-b738-599307a86075.png)
![image](https://user-images.githubusercontent.com/20538091/172213416-13ff3a5f-cb11-482a-8e7f-2e7924a31371.png)

**Environment (please complete the following information):**
ignore

**Additional context**
ignore

**Comment by EdiWang** [comment]
Please restart the website or clear server side cache. Because changes to DB won't refresh cache, count for posts is part of it.
