### ISSUE TITLE
OpenSans-Regular.ttf has incorrect path

### ISSUE THREAD

**Issue by wenhyan** [EdiWang/Moonglade#662]
**Describe the bug**
When i use the install.sh in Deployment，the OpenSans-Regular.ttf  was moved to build directory.
Is this a bug？

**Position**
Moonglade/Deployment/install.sh  --> lines 46

**Environment**
 - OS: Ubuntu 20.04 LTS
 - Moonglade version: 12.3.3

**Comment by EdiWang** [comment]
@Anduin2017 please take a look and work 996 to fix it. Your script, your pot. 😁

**Comment by Anduin2017** [comment]
Ack.
