### ISSUE TITLE
IIS mode deployment cannot add administrator account and modify administrator password

### ISSUE THREAD

**Issue by Lesliewxj** [EdiWang/Moonglade#673]
**Describe the bug**
The background page cannot add an administrator account and modify the administrator password

**To Reproduce**

1. Go to 'https://47.100.54.0/admin'
2. Login with default account.     admin  admin123
3. Click on account, add user, change password

**Screenshots**
![account](https://cdn.staticaly.com/gh/Lesliewxj/lesliewxj-image@master/git-issue/account.7bxsjf34yng0.webp)

**Environment :**
 - OS:  Windows 10
 - Browser ：Chrome
 - Version 70
 
**Server Environment :**
![info](https://cdn.staticaly.com/gh/Lesliewxj/lesliewxj-image@master/git-issue/info.2k1mimufi3w0.webp)

**Comment by Lesliewxj** [comment]
In a few days, I will also write a document on how to deploy through IIS on the window server. You can take a look at it at that time. I encountered a lot of problems, and I solved them all.

**Comment by EdiWang** [comment]
Fixed on master branch, will release in v12.4.0.

**Comment by Lesliewxj** [comment]
okay, thanks a lot !!!

**Comment by Lesliewxj** [comment]
The new problem is that the 405 error has been reported when changing the password and cannot be changed.
Screenshots
![reset-password-error](https://cdn.staticaly.com/gh/Lesliewxj/lesliewxj-image@master/git-issue/reset-password-error.1qhfcsan915s.webp)

**Comment by Lesliewxj** [comment]
@EdiWang

**Comment by EdiWang** [comment]
@Lesliewxj

405 is not a bug for Moonglade. Many http verbs are disabled in IIS by default. You need to manually enable HTTP GET POST PUT DELETE in web.config.

**Comment by Lesliewxj** [comment]
okay, thanks.
