### ISSUE TITLE
Azure Function deployment

### ISSUE THREAD

**Issue by command0r** [EdiWang/Moonglade#678]
**Issue desc.**
There's no clear description of how to build and deploy Azure Function for email notifications. The instruction [here](https://github.com/EdiWang/Moonglade.Notification) does not provide sufficient info on the AZF itself and points to a missing file in the repository (e.g., 'Deploy.ps1' does not exist, while 'AzureQuickDeploy.ps1' does not contain logic for an AZF deployment). 

**Expected behavior**
The AZF is deployed as part of the Deployment routine

**Additional question**
Is there a way to employ Azure SendGrid for email notifications? Any information/context in that regard would be much appreciated.

**Comment by EdiWang** [comment]
The readme file has a incorrect path.

You can find the deployment script here

https://github.com/EdiWang/Moonglade.Notification/blob/master/Azure-Deployment/Deploy.ps1#L68

**Comment by EdiWang** [comment]
The current solution is not using SendGrid, my email account seems to be blocked by SendGrid.

**Comment by command0r** [comment]
Thanks, @EdiWang, I appreciate your prompt reply.
