### ISSUE TITLE
[Question] Normally how much we need to pay for azure to deploy whole system

### ISSUE THREAD

**Issue by minhhungit** [EdiWang/Moonglade#707]
Hi not sure if anyone tried to deploy this, I wonder how much we need to pay for azure to deploy whole system, minimum price, please share your exp

**Comment by minhhungit** [comment]
@EdiWang if you deployed can you please share info about it

**Comment by EdiWang** [comment]
Hi @minhhungit 

This depends on how many services there are and how many users.

For example, my blog is using 14 azure services and costs around 600 USD per month, sometimes when visitors flood, it costs me 1700 USD once.

A minimal deployment of moonglade takes an app service, a SQL database, a storage account, it can be reduced to around 50-100 USD per month, depends on your instance size.

So I don't think this question has any meaning for reference. Everyone's deployment is different.
