### ISSUE TITLE
请求添加到 博客示例

### ISSUE THREAD

**Issue by bicijinlian** [EdiWang/Moonglade#730]
我使用您的程序，建立了自己的博客。请求添加到项目的 博客示例 列表。网址为 https://blog.wanggaofeng.net
![image](https://github.com/EdiWang/Moonglade/assets/10394955/2564b7db-efa3-4a35-aa57-71c8dcd7c1ba)

**Comment by EdiWang** [comment]
Close as added into example blog list.
