### ISSUE TITLE
[WIP] 建议添加自定义排序功能：包括分类、友情连接等模块

### ISSUE THREAD

**Issue by bicijinlian** [EdiWang/Moonglade#731]
建议添加自定义排序功能：包括分类、标签、友情连接等模块。这些模块现在只能默认排序，很希望实现自定义排序功能！
![image](https://github.com/EdiWang/Moonglade/assets/10394955/a1c1e1a5-4be6-496e-b950-192ae8f63af0)

**Comment by EdiWang** [comment]
Thanks for your suggestion. Custom ranking for friend links will be added in v14.1.0, ranking for categories is still under discussion.

**Comment by EdiWang** [comment]
Decision is made to add custom ranking to friend links only.
