### ISSUE TITLE
Cost of Azure

### ISSUE THREAD

**Issue by hyfree** [EdiWang/Moonglade#753]
Cost of Azure
The demo site uses by utilizing as many Azure services as possible, is it possible to share the cost of running this site.
------ZH-CN-----
  Azure 的费用
演示网站通过利用尽可能多的 Azure 服务，是否可以分享运行这些服务的费用。
thank

**Comment by EdiWang** [comment]
My blog site is deployed in 2 Azure regions, West US and East Asia. With all 14 services, it costs around **600 USD** every month. 

Most of the cost is used by the following services

- 2x Azure App Service - P1V2
- 1x Azure SQL Database - S1 20DTU
- 1x Azure Front Door - Premium
- 1x Storage Account - V2
