### ISSUE TITLE
Database Migration from SQL Server to MySQL

### ISSUE THREAD

**Issue by MatinxHT** [EdiWang/Moonglade#820]
**Describe the Issue**
Hello, I am considering migrating the Moonglade system's database from SQL Server to MySQL. The goal is to retain all existing data from SQL Server and perform a seamless migration, ensuring minimal downtime and no data loss.

**Steps or Guidance Needed**
I would appreciate guidance on the specific steps and considerations for this process. In particular, we are looking for advice on:
Tools or best practices for conducting the migration.
Potential challenges or incompatibilities when transferring schema, stored procedures, and data types between the two databases.
Ensuring data integrity and validation post-migration.
Any known performance or optimization issues after switching to MySQL.
Additionally, I haven't come across any related issues concerning database migration for this project. If this has been addressed before, kindly point me to the relevant discussion or documentation.

Any insights or recommendations would be greatly appreciated!

**Environment**
OS: Moonglade on Ubuntu 24 LTS, Database on Windows Server with SQL Server 2019 (15.0)
Moonglade Version: 14.7.1

**Comment by EdiWang** [comment]
MySQL support was added by the community. I personally have no knowledge of MySQL, I'm afraid I could not provide any guide  at this time. 

SQL Server is still the recommended database for Moonglade. Free version of SQL Express would be enough for this system.

**Comment by MatinxHT** [comment]
> MySQL support was added by the community. I personally have no knowledge of MySQL, I'm afraid I could not provide any guide at this time.
> 
> SQL Server is still the recommended database for Moonglade. Free version of SQL Express would be enough for this system.

Thanks for your answer. I will look for a cheaper and more reliable cloud platform to mount my database service. SQL Server migration is much more convenient.
